version: '3'

services:
  tts-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./outputs:/app/outputs
      - ./model:/app/model
      - ./speaker_embeddings.npy:/app/speaker_embeddings.npy
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - DB_NAME=tts_service
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: